st7/
	;------------------------------------------------------
	; SEGMENT MAPPING FILE AUTOMATICALLY GENERATED BY STVD7
	; SHOULD NOT BE MANUALLY MODIFIED.
	; CHANGES WILL BE LOST WHEN FILE IS REGENERATED.
	;------------------------------------------------------
	BYTES			; The following addresses are 8 bits long
	segment byte at 80-17F 'ram0'

	WORDS			; The following addresses are 16 bits long
	segment byte at 180-1FF 'stack'

	WORDS			; The following addresses are 16 bits long
	segment byte at E000-FFDF 'rom'

	WORDS			; The following addresses are 16 bits long
	segment byte at FFE0-FFFF 'vectit'

		END
